import { Bank } from "./schemas";

export const banks: Bank[] = [
  { id: "1", name: "Chase" },
  { id: "2", name: "Bank of America" },
  { id: "3", name: "Wells Fargo" },
  { id: "4", name: "Citibank" },
  { id: "5", name: "U.S. Bank" },
  { id: "6", name: "PNC Bank" },
  { id: "7", name: "Capital One" },
  { id: "8", name: "TD Bank" },
  { id: "9", name: "Truist" },
  { id: "10", name: "Goldman Sachs" },
  { id: "11", name: "Morgan Stanley" },
  { id: "12", name: "Charles Schwab" },
  { id: "13", name: "HSBC" },
  { id: "14", name: "BMO Harris" },
  { id: "15", name: "Fifth Third Bank" },
  { id: "16", name: "Ally Bank" },
  { id: "17", name: "Discover Bank" },
  { id: "18", name: "Synchrony Bank" },
  { id: "19", name: "Citizens Bank" },
  { id: "20", name: "KeyBank" },
  { id: "21", name: "Regions Bank" },
  { id: "22", name: "Huntington Bank" },
  { id: "23", name: "M&T Bank" },
  { id: "24", name: "First Republic" },
  { id: "25", name: "Santander Bank" },
  { id: "26", name: "Navy Federal" },
  { id: "27", name: "USAA" },
  { id: "28", name: "American Express" },
  { id: "29", name: "SoFi" },
  { id: "30", name: "Chime" },
];